// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MapView",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "MapView",
            targets: ["AppModule"],
            bundleIdentifier: "com.diconium.MapView",
            teamIdentifier: "TD2M5HQ3P7",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationAlwaysAndWhenInUse(purposeString: "We need to show a Map in the App. ")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/vincentneo/CoreGPX.git", "0.9.0"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CoreGPX", package: "coregpx")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)